apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
  namespace: lion-namespace
  labels:
    run: kubia
spec:
  replicas: 2
  selector:
    run: kubia
  template:
    metadata:
      labels:
        run: kubia
    spec:
      containers:
      - name: kubia
        image: 85117921/myhello-app:v1.1.10
        ports:
        - containerPort: 8080
          protocol: TCP
      
